### ISSUE TITLE
Error when trying to lint schemas with circular references

### ISSUE THREAD

**Issue by rafasouzaandrade** [stoplightio/spectral#870] opened 2019-12-20 13:20 UTC
When we run the command spectral lint in our project, we are having the following error

` 1:1  error  invalid-ref  ENOENT: no such file or directory, open '<path>/openapi-simplifed.yaml'`

We are running the command like this

`spectral lint schemas-2/*.yaml`

You can try to run the spectral lint in this sample to test.
[github-error-sample.zip](https://github.com/stoplightio/spectral/files/3988420/github-error-sample.zip)

Thanks

**Comment by P0lip** [comment] 2020-01-09 12:00
Forgot to post an update on this one.
I investigated the issue a few days ago and found out its caused by json-ref-resolver and its caching mechanism.
We haven't fixed that yet, but it's a WIP.

**Comment by kylesykes** [comment] 2020-01-21 20:22
@P0lip would this also be the cause for inconsistent failures when linting with v5?  I'm attaching an example that replicates the inconsistent failures we are seeing (which has been maddening to debug).

The screenshot below is running the attached example multiple times in a row.  I feel like it would be really weird if `json-ref-resolver`s caching issues extended beyond individual runs of Spectral (meaning the cache is happening somewhere on my machine and corrupting future runs of Spectral?)

I figured I would comment here before opening a new issue if it happens to be symptoms of the same behavior.  If you don't think this is causing it, I can open a new issue with the same information to better track the cause.

[stoplight_breaking_example.zip](https://github.com/stoplightio/spectral/files/4093514/stoplight_breaking_example.zip)
![image](https://user-images.githubusercontent.com/3663141/72839972-e4b3d200-3c58-11ea-871e-41e136d91427.png)

**Comment by lehphyro** [comment] 2020-02-08 12:28
We have the same issue, please note that it's not about circular references but rather just following references properly so the issue title should be fixed.

**Comment by P0lip** [comment] 2020-02-12 11:56
@kylesykes @lehphyro 
Hey folks.
Sorry not keeping you waiting.
The fix is under way - going to take a while, but it's in progress.

> The screenshot below is running the attached example multiple times in a row. I feel like it would be really weird if json-ref-resolvers caching issues extended beyond individual runs of Spectral (meaning the cache is happening somewhere on my machine and corrupting future runs of Spectral?)

answering your question - that is totally possible.

**Comment by philsturgeon** [comment] 2020-04-28 16:11
@P0lip did we get this one sorted out?

**Comment by P0lip** [comment] 2020-04-28 19:20
Not yet. I was hoping to fix json-ref-resolver and started working on the fix, but since we decided to abandon it, it didn't move any forward.

**Comment by philsturgeon** [comment] 2020-04-28 21:48
Ok, let's consider this issue superseded by #1054. Moving to a popular, well used JSON Ref package should be a big win for trouble like this, especially with $ref changes coming in OAS3.1.

**Closed by philsturgeon** 2020-04-28 21:48 UTC
Labels: bug
