### ISSUE TITLE
oas3-valid-media-example reports on missing examples where response body uses a required but read only property

### ISSUE THREAD

**Issue by savage-alex** [stoplightio/spectral#2490] opened 2023-06-19 14:26 UTC
Given a schema that contains a readonly and required property such as fooId
When this schema is used in a response body and a schema level example is provided without fooId (its read only)
The OAS3 valid media example error is thrown even though the schema is valid vs openAPI3 rules on read only required properties in requestBodies.

Thanks

**Comment by LasneF** [comment] 2023-06-21 09:44
isnt it a duplicate of #1274

**Comment by mnaumanali94** [comment] 2023-07-27 06:20
Duplicate of #1274

**Closed as completed by mnaumanali94** 2023-07-27 06:20 UTC
