### ISSUE TITLE
spectral does not resolve path->parameters->$ref

### ISSUE THREAD

**Issue by brianmrock** [stoplightio/spectral#323] opened 2019-07-06 19:23 UTC
**Detective mod**e: Find the github issue, see if you can get more information out of the user, if not then close this down. 

```
yaml/domains/{domainCode}:parameters:

$ref: "#/components/parameters/domainCode"
```

The domainCode is defined in `components/parameters/domainCode` but it complains:```

name: path-paramssummary: Path parameters are correct and valid.message: >-The path "*/domains/{domainCode}/models*" uses a parameter"*{domainCode}*" that does not have a corresponding definition.

To fix, add a path parameter with the name "*domainCode*".path:

paths

'/domains/{domainCode}/models'severity: 50severityLabel: error```

**Comment by P0lip** [comment] 2019-07-07 19:49
It's a dupe of https://github.com/stoplightio/spectral/issues/108

**Closed by P0lip** 2019-07-07 19:49 UTC
Labels: bug
