### ISSUE TITLE
Docker - "spectral lint --version" doesn't work

### ISSUE THREAD

**Issue by vlauciani** [stoplightio/spectral#1483] opened 2021-01-18 17:05 UTC
Checking the version on Docker image, the output is always `0.0.0`:
```
$ docker run --rm stoplight/spectral lint --version
0.0.0
$
```

**Comment by philsturgeon** [comment] 2021-05-04 19:39
Thanks for reporting this, docker really needs some work. This is a duplicate of #1191 though so I'll keep the first one open.

**Closed by philsturgeon** 2021-05-04 19:39 UTC
Labels: bug
