### ISSUE TITLE
can `spectral supported` release of arm64 architecture ？

### ISSUE THREAD

**Issue by Jeremy-boo** [stoplightio/spectral#2279] opened 2022-09-16 10:05 UTC
**User story.**
There is currently no official binary release for the arm64 architecture，As the arm architecture becomes more and more popular, everyone is more and more urgent for the binary files of the arm architecture

**Is your feature request related to a problem?**

**Describe the solution you'd like**

**Additional context**

**Comment by mnaumanali94** [comment] 2022-09-23 16:17
This would be a very nice addition. Would you be interested in creating a PR for this? 🙏🏼

**Comment by mnaumanali94** [comment] 2023-03-23 16:16
Duplicate of: https://github.com/stoplightio/spectral/issues/2189

**Closed as completed by mnaumanali94** 2023-03-23 16:16 UTC
Labels: enhancement
