### ISSUE TITLE
Docs for validating objects against schemas

### ISSUE THREAD

**Issue by denver-HJS** [stoplightio/spectral#410] opened 2019-07-29 20:40 UTC
**Chore summary**
The README.md says the following under the FAQs:

> How is this different than Ajv?
> 
> Ajv is a JSON Schema validator, not a linter. Spectral does expose a schema function that you can use in your rules to validate all or part of the target object with JSON Schema (Ajv is used under the hood). However, Spectral also provides a number of other functions and utilities that you can use to build up a linting ruleset to validates things that JSON Schema is not well suited for.

I wasn't able to find any examples of using the exposed `schema` function, and I'm having a hard time conceptualizing that myself.

**Tasks**
- [ ] Add sample code and/or working examples of validating a given object in memory against an oas3 resource schema

**Comment by philsturgeon** [comment] 2019-07-31 11:25
@denver-HJS hey, yeah we're a little behind on the docs but @P0lip  is on the case already: #412 

Until the docs are sorted out, you can take a look at the core rulesets to as an example of how things work. Right here we use JSON Schema to make sure the servers array is looking good. 

https://github.com/stoplightio/spectral/blob/develop/src/rulesets/oas3/index.json#L4

Use the schema function, with a `schema` functionOption, then just shove your JSON Schema in that. Job done :D 

I'll close this one as it's a duplicate of #302, but if you have any more questions you can ask here, or wait for those docs. Subscribe to #302 to get an email when the work is done.

**Closed by philsturgeon** 2019-07-31 11:25 UTC
